- hosts: all
  become: yes
  tasks:
  - name: Add an apt key by id from a keyserver
    apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
  - name: Install valut package
    package:
      name: gpg
      state: present
                
  - name: Add repository
    apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_facts.lsb.codename }} main"
      state: present

  - name: Install valut package
    package:
      name: vault
      state: present
