- hosts: all
  become: yes
  tasks:
  - name: Add an apt key by id from a keyserver
    apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
  - debug:
      msg: "{{ ansible_facts }}"
        
  #- name: Add repository
   # apt_repository:
   #   repo: deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main
   #   state: present
