- hosts: all
  become: yes
  tasks:        
  - name: Install valut package
    package:
      name: gpg
      state: present
                
  - name: Add repository
    shell: |
      wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg >/dev/null
      gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_facts.lsb.codename }} main

  - name: Install valut package
    package:
      name: vault
      state: present
